### ISSUE TITLE
what is contrastive dataset?

### ISSUE THREAD

**Issue by azarijafari** [derincen/multi-lingual-nli#1]
What is the use of contrastive dataset?
create_contrastive_dataset(data_en_target, config.experiment_lang, 100000)
In this line you random displace rows and words of each sentence.
What is the reason?
Which part of your paper refer to this?
thanks

**Comment by adcengiz** [comment]
Let's say we are calculating the loss of the sentence aligner using the sentence "There is a cat in the room" and its translation to Turkish "Odada bir kedi var". Now we want, once the aligner loss is minimized, those two sentences to appear close enough in space that the discriminator - and the NLI classifier - "thinks" that the Turkish sentence is actually in English. But on the other hand, we don't want "There is a cat in the room" to appear close to **_any_** Turkish sentence. Therefore by shuffling the Turkish sentences we obtain a second, contrastive, dataset that samples those "any" Turkish sentences that are randomly drawn from the Turkish batch. **We compute the contrastive loss and add it to the aligner loss so that the aligner brings the correct translations together while at the same time it brings random or incorrect translations further apart.**
